# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nithyanandam  
email: arjun@skuchain.com 
description: > # this means to ignore newlines until "baseurl:"
  Demo site integrating machine transcription service into YouTube. 
baseurl: "http://arjoona.github.io/youtube/" # the subpath of your site, e.g. /blog
url: "https://github.com/arjoona/youtube" # the base hostname & protocol for your site
twitter_username: ' ' 
github_username: arjoona 

# Build settings
markdown: kramdown
